const $=(s,p=document)=>p.querySelector(s);const cfg=window.KOMOREBI_CONFIG||{};const configured=cfg.supabaseUrl&&!cfg.supabaseUrl.startsWith('YOUR_')&&cfg.supabasePublishableKey&&!cfg.supabasePublishableKey.startsWith('YOUR_');const LOCAL_KEY='komorebi-vocabulary-local-v1';let db=null,currentUser=null,mode='local';const esc=v=>String(v??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));
function setState(message,on=false){$('#syncState span').textContent=message;$('#syncState').classList.toggle('online',on)}
function localWords(){try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]')}catch{return[]}}
function saveLocalWords(words){localStorage.setItem(LOCAL_KEY,JSON.stringify(words))}
function setToday(){if(!$('#dateAdded').value)$('#dateAdded').value=new Date().toISOString().slice(0,10)}
async function init(){setToday();const supabaseLibrary=window.supabase||await(window.KOMOREBI_SUPABASE_READY||Promise.resolve(null));if(!configured||!supabaseLibrary){$('#setupMessage').hidden=false;enableLocal('Cloud sync is unavailable—saving privately on this device.');return}try{db=supabaseLibrary.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const {data:{session}}=await db.auth.getSession();await showSession(session);db.auth.onAuthStateChange((_event,session)=>setTimeout(()=>showSession(session),0))}catch(error){enableLocal('Supabase could not connect—using this device instead.')}}
async function showSession(session){currentUser=session?.user||null;if(!currentUser){mode='cloud';$('#authCard').hidden=false;$('#wordWorkspace').hidden=true;setState('Sign in to sync, or continue on this device');return}mode='cloud';$('#authCard').hidden=true;$('#setupMessage').hidden=true;$('#wordWorkspace').hidden=false;$('#signOut').hidden=false;$('#userEmail').textContent=currentUser.email;setState('Private wordbook synced',true);await loadWords()}
function enableLocal(message='Saving privately on this device'){mode='local';currentUser=null;$('#authCard').hidden=true;$('#wordWorkspace').hidden=false;$('#signOut').hidden=true;$('#userEmail').textContent='This device only';setState(message,false);loadWords()}
$('#localMode').addEventListener('click',()=>enableLocal());
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();if(!db){enableLocal();return}const note=$('#authNote'),email=$('#authEmail').value.trim();note.textContent='Sending…';const redirect=location.href.split('#')[0];const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:redirect}});note.textContent=error?error.message:'Check your email for the private sign-in link.'});
$('#signOut').addEventListener('click',()=>db?.auth.signOut());
function formRecord(){const category=$('#wordCategory').value;return{word:$('#word').value.trim(),reading:$('#reading').value.trim(),meaning:$('#meaning').value.trim(),example_japanese:$('#exampleJapanese').value.trim()||null,example_english:$('#exampleEnglish').value.trim()||null,category,notes:$('#wordNotes').value.trim()||null,date_added:$('#dateAdded').value||new Date().toISOString().slice(0,10),source:category,updated_at:new Date().toISOString()}}
$('#wordForm').addEventListener('submit',async e=>{e.preventDefault();const note=$('#wordNote'),record=formRecord();note.className='';note.textContent='Saving…';if(mode==='local'){let words=localWords(),existing=words.find(item=>item.word===record.word);if(existing)Object.assign(existing,record);else words.unshift({...record,id:crypto.randomUUID?.()||String(Date.now()),created_at:new Date().toISOString()});saveLocalWords(words);note.textContent='Saved on this device—this word can appear as Word of the Day here.';note.className='success';e.target.reset();setToday();await loadWords();return}const {error}=await db.from('vocabulary').upsert({...record,user_id:currentUser.id},{onConflict:'user_id,word'});if(error){note.textContent='Cloud save failed: '+error.message+' You can choose device-only mode above.';note.className='error';return}note.textContent='Saved—this word will sync across your signed-in devices.';note.className='success';e.target.reset();setToday();await loadWords()});
async function loadWords(){let data=[];if(mode==='local')data=localWords();else{const result=await db.from('vocabulary').select('*').order('date_added',{ascending:false});if(result.error){$('#wordList').innerHTML='<p class="word-list-empty">Sync is temporarily unavailable. Your page is still safe; try again later or use device-only mode.</p>';return}data=result.data||[]}renderWords(data)}
function renderWords(data){$('#wordCount').textContent=data.length+' word'+(data.length===1?'':'s');$('#wordList').innerHTML=data.length?data.map(item=>'<article class="saved-word"><div><strong lang="ja">'+esc(item.word)+'</strong><span lang="ja">'+esc(item.reading)+'</span></div><div><b>'+esc(item.meaning)+'</b>'+(item.example_japanese?'<p lang="ja">'+esc(item.example_japanese)+'</p>':'')+(item.example_english?'<em>'+esc(item.example_english)+'</em>':'')+'<small>'+esc(item.category||item.source||'General')+' · '+esc(item.date_added||'')+'</small>'+(item.notes?'<span class="word-notes">'+esc(item.notes)+'</span>':'')+'</div><button data-delete="'+item.id+'" aria-label="Delete '+esc(item.word)+'">×</button></article>').join(''):'<p class="word-list-empty">Your first saved word will appear here.</p>'}
$('#wordList').addEventListener('click',async e=>{const button=e.target.closest('[data-delete]');if(!button)return;if(!confirm('Delete this saved word?'))return;button.disabled=true;if(mode==='local'){saveLocalWords(localWords().filter(item=>item.id!==button.dataset.delete));await loadWords();return}const {error}=await db.from('vocabulary').delete().eq('id',button.dataset.delete);if(error){button.disabled=false;return}await loadWords()});init();
