const genres={bluegrass:['Salt Creek','Traditional · Crosspicking · 112 bpm'],blues:['Stormy Monday','T-Bone Walker · 12-bar blues · 68 bpm'],classical:['Lágrima','Francisco Tárrega · Prelude · Andante'],theory:['Circle of Fifths','F–C–G–D–A–E–B']};
document.querySelectorAll('.tabs button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));button.classList.add('active');const item=genres[button.dataset.genre];document.querySelector('#piece').textContent=item[0];document.querySelector('#pieceMeta').textContent=item[1]}));
const theoryNotes=[['IV','Subdominant','In G major, the IV chord is C major: C–E–G.'],['V','Dominant','In G major, the V chord is D major: D–F♯–A.'],['m3','Minor third','A minor third spans three semitones, such as E to G.'],['M3','Major third','A major third spans four semitones, such as G to B.'],['P5','Perfect fifth','A perfect fifth spans seven semitones, such as G to D.']];let theoryIndex=0;
document.querySelector('#newTheory').addEventListener('click',()=>{theoryIndex=(theoryIndex+1)%theoryNotes.length;const n=theoryNotes[theoryIndex];document.querySelector('#theoryMark').textContent=n[0];document.querySelector('#theoryTitle').textContent=n[1];document.querySelector('#theoryText').textContent=n[2]});
const storageKey='komorebi-youtube-lessons-v1';let lessons=[];try{lessons=JSON.parse(localStorage.getItem(storageKey)||'[]')}catch{}
const escapeText=value=>String(value).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));
function youtubeId(value){try{const url=new URL(value);if(url.hostname==='youtu.be')return url.pathname.split('/').filter(Boolean)[0]||null;if(url.hostname.includes('youtube.com'))return url.searchParams.get('v')||url.pathname.split('/').filter(Boolean).slice(-1)[0]||null}catch{}return null}
function saveLessons(){localStorage.setItem(storageKey,JSON.stringify(lessons))}
function playLesson(index,type='original'){const item=lessons[index];if(!item)return;const lesson=type==='lesson'&&item.lessonId;const id=lesson?item.lessonId:item.originalId,url=lesson?item.lessonUrl:item.originalUrl;document.querySelector('#ytEmpty').hidden=true;document.querySelector('#ytActive').hidden=false;document.querySelector('#ytFrame').src='https://www.youtube-nocookie.com/embed/'+id+'?rel=0';document.querySelector('#ytActiveStyle').textContent=item.style+' · '+(lesson?'LESSON':'ORIGINAL');document.querySelector('#ytActiveTitle').textContent=item.title;const open=document.querySelector('#ytOpen');open.href=url;open.textContent='Open '+(lesson?'lesson':'original')+' on YouTube ↗'}
function renderLessons(){const library=document.querySelector('#ytLibrary');document.querySelector('#ytCount').textContent=lessons.length+' song'+(lessons.length===1?'':'s');if(!lessons.length){library.innerHTML='<div class="yt-library-empty">No saved links.</div>';return}library.innerHTML=lessons.map((item,index)=>'<article class="yt-resource"><div class="yt-resource-copy"><small>'+escapeText(item.style)+(item.lessonId?' · lesson included':'')+'</small><strong>'+escapeText(item.title)+'</strong><div class="yt-resource-actions"><button data-play-index="'+index+'" data-play-type="original">Original</button>'+(item.lessonId?'<button data-play-index="'+index+'" data-play-type="lesson">Lesson</button>':'')+'</div></div><button class="yt-delete" data-delete-index="'+index+'" aria-label="Remove">×</button></article>').join('')}
document.querySelector('#youtubeForm').addEventListener('submit',event=>{event.preventDefault();const title=document.querySelector('#ytTitle').value.trim(),originalUrl=document.querySelector('#ytUrl').value.trim(),lessonUrl=document.querySelector('#ytLessonUrl').value.trim(),style=document.querySelector('#ytStyle').value,originalId=youtubeId(originalUrl),lessonId=lessonUrl?youtubeId(lessonUrl):null,note=document.querySelector('#ytFormNote');if(!originalId){note.textContent='Enter a valid YouTube URL.';return}if(lessonUrl&&!lessonId){note.textContent='The lesson URL is not valid.';return}lessons.unshift({title,style,originalId,originalUrl:'https://www.youtube.com/watch?v='+originalId,lessonId,lessonUrl:lessonId?'https://www.youtube.com/watch?v='+lessonId:null});saveLessons();renderLessons();playLesson(0);event.target.reset();note.textContent='Saved privately on this device.'});
document.querySelector('#ytLibrary').addEventListener('click',event=>{const play=event.target.closest('[data-play-index]'),remove=event.target.closest('[data-delete-index]');if(play)playLesson(Number(play.dataset.playIndex),play.dataset.playType);if(remove){if(!confirm('Remove this saved song or lesson?'))return;lessons.splice(Number(remove.dataset.deleteIndex),1);saveLessons();renderLessons();if(!lessons.length){document.querySelector('#ytActive').hidden=true;document.querySelector('#ytEmpty').hidden=false;document.querySelector('#ytFrame').src=''}}});renderLessons();
