'use strict';

const TIMER_KEY = 'komorebi-running-timer-v1';
const catalog = window.KomorebiActivities;
const practiceStore = window.KomorebiPractice;
const dayKey = value => new Date(value).toLocaleDateString('en-CA');
let timerInterval = null;

function readTimer() { try { return JSON.parse(localStorage.getItem(TIMER_KEY) || 'null'); } catch { return null; } }
function writeTimer(timer) { if (timer) localStorage.setItem(TIMER_KEY, JSON.stringify(timer)); else localStorage.removeItem(TIMER_KEY); }
function formatElapsed(milliseconds) { const seconds = Math.max(0, Math.floor(milliseconds / 1000)), hours = Math.floor(seconds / 3600), minutes = Math.floor((seconds % 3600) / 60); return `${hours ? `${hours}:` : ''}${String(minutes).padStart(hours ? 2 : 1, '0')}:${String(seconds % 60).padStart(2, '0')}`; }

function streakFor(log, activityId) { const included = new Set(catalog.descendants(activityId)), days = new Set(log.filter(item => included.has(catalog.activityId(item))).map(item => item.day || dayKey(item.logged_at || item.at))), today = dayKey(Date.now()); let streak = 0, cursor = new Date(); if (!days.has(today)) cursor.setDate(cursor.getDate() - 1); while (days.has(dayKey(cursor))) { streak += 1; cursor.setDate(cursor.getDate() - 1); } return streak; }
function weeklyMinutes(log, activityId) { const start = new Date(); start.setDate(start.getDate() - ((start.getDay() + 6) % 7)); start.setHours(0,0,0,0); const ids = activityId ? new Set(catalog.descendants(activityId)) : null; return log.filter(item => new Date(item.logged_at || item.at) >= start && (!ids || ids.has(catalog.activityId(item)))).reduce((sum,item)=>sum+Number(item.minutes||0),0); }

function drawPractice(log) { const today = dayKey(Date.now()), todayMinutes = log.filter(item => (item.day || dayKey(item.logged_at || item.at)) === today).reduce((sum,item)=>sum+Number(item.minutes||0),0); document.querySelector('#practiceSummary').textContent = todayMinutes ? `${todayMinutes} minutes logged today.` : 'Nothing logged today yet.'; document.querySelector('#japaneseStreak').textContent = String(streakFor(log,'japanese')); document.querySelector('#musicStreak').textContent = String(streakFor(log,'music')); document.querySelector('#practiceWeek').textContent = String(weeklyMinutes(log)); }
function renderActivityButtons() { const items = catalog.currentLoggable(), timer = readTimer(), root = document.querySelector('#practiceActivityButtons'); root.innerHTML = items.map(item => `<article class="quick-activity"><strong>${catalog.label(item.id)}</strong><div class="quick-activity-controls"><label class="custom-minutes"><span>Minutes</span><input type="number" min="0" max="1440" step="1" value="0" inputmode="numeric" data-custom-minutes="${item.id}" aria-label="Minutes for ${catalog.label(item.id)}"></label><button type="button" data-custom-log="${item.id}">Log</button><button type="button" data-start-timer="${item.id}" ${timer ? 'disabled' : ''}>Start</button></div></article>`).join(''); }
function drawGoals(log, goals) { const root = document.querySelector('#homeGoalProgress'); if (!root) return; root.innerHTML = goals.length ? goals.map(goal => { const item = catalog.read().find(value => value.name === goal.activity || value.id === goal.activity), id = item?.id || goal.activity, minutes = weeklyMinutes(log,id), percent = Math.min(100,Math.round(minutes/goal.targetMinutes*100)), label = item ? catalog.label(item.id) : goal.activity; return `<article><span><b>${label}</b><small>${minutes} / ${goal.targetMinutes} min</small></span><i><em style="width:${percent}%"></em></i></article>`; }).join('') : '<p>No weekly goals set yet. <a href="practice-goals.html">Set goals</a></p>'; }
function drawSync(state) { const indicator = document.querySelector('#practiceSyncState'); if (!indicator) return; indicator.textContent = state.message; indicator.dataset.state = state.status; document.body.classList.toggle('practice-loading',state.status==='loading'); }
function renderTimer() { const timer = readTimer(), bar = document.querySelector('#practiceTimer'); clearInterval(timerInterval); if (!timer) { bar.hidden = true; renderActivityButtons(); return; } bar.hidden = false; document.querySelector('#practiceTimerName').textContent = catalog.label(timer.activityId); const tick = () => document.querySelector('#practiceElapsed').textContent = formatElapsed(Date.now()-timer.startedAt); tick(); timerInterval = setInterval(tick,1000); renderActivityButtons(); }

document.querySelector('#practiceActivityButtons').addEventListener('click',async event=>{ const custom=event.target.closest('[data-custom-log]'),start=event.target.closest('[data-start-timer]'); if(custom){const input=custom.closest('.quick-activity').querySelector('[data-custom-minutes]'),minutes=Math.round(Number(input.value));if(!Number.isFinite(minutes)||minutes<1||minutes>1440){input.focus();input.setCustomValidity('Enter between 1 and 1440 minutes.');input.reportValidity();return}input.setCustomValidity('');custom.disabled=true;await practiceStore.createLog({activityId:custom.dataset.customLog,minutes,logged_at:new Date().toISOString(),day:dayKey(Date.now()),notes:''});input.value='0';custom.disabled=false} if(start){writeTimer({activityId:start.dataset.startTimer,startedAt:Date.now()});renderTimer()} });
document.querySelector('#stopPracticeTimer').addEventListener('click',async()=>{const timer=readTimer();if(!timer)return;const minutes=Math.max(1,Math.ceil((Date.now()-timer.startedAt)/60000));writeTimer(null);renderTimer();await practiceStore.createLog({activityId:timer.activityId,minutes,logged_at:new Date().toISOString(),day:dayKey(Date.now()),notes:''})});
practiceStore.subscribe(state=>{drawSync(state);drawPractice(state.logs);drawGoals(state.logs,state.goals)});
renderActivityButtons();renderTimer();
